# Generated by Django 2.2.11 on 2021-11-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakingcoin',
            name='maxdeposit',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Макс.депозит'),
        ),
        migrations.AddField(
            model_name='stakingcoin',
            name='mindeposit',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Мин.депозит'),
        ),
    ]
